API Doc Specification
dapr/sig-sdk-spec pull request #17
Opened 2022-09-04 19:03 UTC by rabollin

Signed-off-by: rabollin <rabollin@microsoft.com>

2022-09-14 16:36 UTC, artursouza requested changes

2022-09-14 16:36 UTC, artursouza commented on Docs/API-Documentation
> +# SDK Documentation
How is that different from the current spec template we have?

2022-09-14 16:40 UTC, rabollin commented
This is the template we should be following for SDK documentation, so that the same template we will be using it for producing the documents for all SDKs we support today and also write new documentation.  My understanding of the Spec template you had described is primarily to detail the technical implementation of the SDK should follow.

2024-12-19 01:26 UTC, msfussell commented
Closing PR, due to archive

2024-12-19 01:26 UTC, closed without merging